spring:
  profiles:
    active: dev

# DEV properties
---
spring:
  config:
    activate:
      on-profile: dev

banco:
  azul:
    estados:
      cuenta:
        docuware:
          url: ${DOCUWARE_SERVER}
          user: ${DOCUWARE_USER}
          password: ${DOCUWARE_PASSWORD}
          idArchivador: ${ID_ARCHIVADOR}
        directorio:
          ect: ${ECT_DIRECTORY}
          ecc: ${ECC_DIRECTORY}
          indexados: ${INDEXADOS_DIRECTORY}
          metadata: ${METADATA_FILE}
        thread:
          maxThreads: ${MAX_WORKERS}
        schedule:
          cron: ${SCHEDULE}
          maxExecutionTime: ${MAX_EXECUTION_DURATION_SECONDS}


# QA properties
---
spring:
  config:
    activate:
      on-profile: qa

banco:
  azul:
    estados:
      cuenta:
        docuware:
          url: ${DOCUWARE_SERVER}
          user: ${DOCUWARE_USER}
          password: ${DOCUWARE_PASSWORD}
          idArchivador: ${ID_ARCHIVADOR}
        directorio:
          ect: ${ECT_DIRECTORY}
          ecc: ${ECC_DIRECTORY}
          indexados: ${INDEXADOS_DIRECTORY}
          metadata: ${METADATA_FILE}
        thread:
          maxThreads: ${MAX_WORKERS}
        schedule:
          cron: ${SCHEDULE}
          maxExecutionTime: ${MAX_EXECUTION_DURATION_SECONDS}

# PROD properties
---
spring:
  config:
    activate:
      on-profile: prod

banco:
  azul:
    estados:
      cuenta:
        docuware:
          url: ${DOCUWARE_SERVER}
          user: ${DOCUWARE_USER}
          password: ${DOCUWARE_PASSWORD}
          idArchivador: ${ID_ARCHIVADOR}
        directorio:
          ect: ${ECT_DIRECTORY}
          ecc: ${ECC_DIRECTORY}
          indexados: ${INDEXADOS_DIRECTORY}
          metadata: ${METADATA_FILE}
        thread:
          maxThreads: ${MAX_WORKERS}
        schedule:
          cron: ${SCHEDULE}
          maxExecutionTime: ${MAX_EXECUTION_DURATION_SECONDS}