spring:
  profiles:
    default: dev

# DEV properties
---
spring:
  config:
    activate:
      on-profile: dev

banco:
  azul:
    estados:
      cuenta:
        docuware:
          url: "http://172.29.1.115/DWDES/ServiciosDW.svc/"
          user: bancoAzul
          password: BAzul2017
          idArchivador: 07272c0a-2916-47a4-947f-41c0cc4864e1
        directorio:
          ect: C:\DOCS_TEST\ECT
          ecc: C:\DOCS_TEST\ECC
          indexados: C:\ESTADOS_CUENTA_INDEXADOS
          metadata: metadata.txt

# QA properties
---
spring:
  config:
    activate:
      on-profile: qa

banco:
  azul:
    estados:
      cuenta:
        docuware:
          url: "http://172.29.1.115/DWDES/ServiciosDW.svc/"
          user: bancoAzul
          password: BAzul2017
          idArchivador: 07272c0a-2916-47a4-947f-41c0cc4864e1
        directorio:
          ect: C:\DOCS_TEST\ECT
          ecc: C:\DOCS_TEST\ECC
          indexados: C:\ESTADOS_CUENTA_INDEXADOS
          metadata: metadata.txt

# PROD properties
---
spring:
  config:
    activate:
      on-profile: prod

banco:
  azul:
    estados:
      cuenta:
        docuware:
          url: "http://172.29.1.115/DWDES/ServiciosDW.svc/"
          user: bancoAzul
          password: BAzul2017
          idArchivador: 07272c0a-2916-47a4-947f-41c0cc4864e1
        directorio:
          ect: C:\DOCS_TEST\ECT
          ecc: C:\DOCS_TEST\ECC
          indexados: C:\ESTADOS_CUENTA_INDEXADOS
          metadata: metadata.txt
